#!/bin/bash
# Perform template substitution in /zimbra/zimbra-config then configure the system
# Expects the following environment variables to be set:
#   HOSTNAME (from specification in the docker-compose file; e.g., 'zimbra-1')
#   ZIMBRA_DEFAULT_DOMAIN
#   ZIMBRA_HOST_NAME
#   TIME_ZONE_ID
#   ADMIN_PW
#   LDAP_ADMIN_PW
#   LDAP_AMAVIS_PW
#   LDAP_POSTFIX_PW
#   LDAP_REPLICATION_PW
#   LDAP_ROOT_PW
#   LDAP_BES_PW
#   LDAP_NGINX_PW
# Also reconfigures tzdata.  Expects these environment variables for that:
#   TZDATA_AREA
#   TZDATA_ZONE
#

SLEEP_SECS=10
# Add entry in /etc/hosts from ZIMBRA_HOST_NAME
# First check to make sure it hasn't already been appliec
grep -q "${ZIMBRA_HOST_NAME}" /etc/hosts
if [ $? != 0 ]; then
    host_address=$(grep "${HOSTNAME}" /etc/hosts | awk '{print $1}')
    echo "Adding mapping for ${ZIMBRA_HOST_NAME} to ${host_address} in /etc/hosts"
    cat /etc/hosts |  sed  -e "s/zimbra/${ZIMBRA_HOST_NAME} zimbra/" >  /tmp/hosts
    cp /tmp/hosts /etc/hosts
else
    echo "An entry for ${ZIMBRA_HOST_NAME} is already present in /etc/hosts"
fi

rm -f /etc/timezone /etc/localtime
echo "tzdata tzdata/Areas select ${TZDATA_AREA}" > /tmp/tzdata.txt
echo "tzdata tzdata/Zones/${TZDATA_AREA} select ${TZDATA_ZONE}" >> /tmp/tzdata.txt
export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true && \
    debconf-set-selections /tmp/tzdata.txt && \
    sudo dpkg-reconfigure -f noninteractive tzdata

grep -q 'CONFIG SESSION COMPLETE' /opt/zimbra/.install_history
if [ $? -eq 0 ]
then
    crontab -u zimbra /opt/zimbra/backup/crontab.bak
    cp /opt/zimbra/backup/60-zimbra.conf.bak /etc/rsyslog.d/60-zimbra.conf
    service rsyslog restart
    sudo -i -u zimbra zmcontrol start
    echo "SYSTEM ALREADY CONFIGURED"
else
    sed -i.bak \
        -e "s/ZIMBRA_HOST_NAME/${ZIMBRA_HOST_NAME}/" \
        -e "s/ZIMBRA_DEFAULT_DOMAIN/${ZIMBRA_DEFAULT_DOMAIN}/" \
        -e "s/TIME_ZONE_ID/${TIME_ZONE_ID}/" \
        -e "s/LDAP_ADMIN_PW/${LDAP_ADMIN_PW}/" \
        -e "s/ADMIN_PW/${ADMIN_PW}/" \
        -e "s/LDAP_AMAVIS_PW/${LDAP_AMAVIS_PW}/" \
        -e "s/LDAP_POSTFIX_PW/${LDAP_POSTFIX_PW}/" \
        -e "s/LDAP_REPLICATION_PW/${LDAP_REPLICATION_PW}/" \
        -e "s/LDAP_ROOT_PW/${LDAP_ROOT_PW}/" \
        -e "s/LDAP_BES_PW/${LDAP_BES_PW}/" \
        -e "s/LDAP_NGINX_PW/${LDAP_NGINX_PW}/" \
        /zimbra/zimbra-config

        /opt/zimbra/libexec/zmsetup.pl -c /zimbra/zimbra-config
        sudo -i -u zimbra /bin/bash -c "crontab -l > /opt/zimbra/backup/crontab.bak"
        cp /etc/rsyslog.d/60-zimbra.conf /opt/zimbra/backup/60-zimbra.conf.bak

        echo "Allow unauthenticated PINGs. This is required by the SOAP-Harness tests"
        sudo -i -u zimbra zmlocalconfig -e allow_unauthed_ping=true
        sudo -i -u zimbra zmmailboxdctl restart
        echo "Enable local mail delivery"
        sudo -i -u zimbra zmprov mcf zimbraMtaLmtpHostLookup native
        sudo -i -u zimbra zmmtactl restart
     
fi
# Startup and configure STAF
export PATH=/usr/local/staf/bin:$PATH
echo 'PATH=/usr/local/staf/bin:$PATH' >> /root/.bashrc
echo "starting STAF. output to /opt/zimbra/log/staf.log."
# NOTE: will see this error if you are watching the logs:
#       STAFProcess::processMonitorThread: Error opening /dev/tty, errno: 6
# That is OK. See: http://staf.sourceforge.net/current2x/STAFFAQ.htm#d0e332
/usr/local/staf/startSTAFProc.sh >/opt/zimbra/log/staf.log 2>&1 &
sleep ${SLEEP_SECS}
echo "adding STAF services"
STAF local service add service LOG LIBRARY STAFLog
echo "setting STAF trust level to 5"
STAF local TRUST SET MACHINE '*' LEVEL 5
echo "SETUP COMPLETE"
/bin/sleep infinity

